// Datos de ejemplo. Cuando conectes una API, reemplazá este arreglo por un fetch
// y mantené la misma forma de objeto para no tocar los componentes.

export const CATEGORIAS = ['Vestidos', 'Tops', 'Pantalones', 'Calzado', 'Accesorios']

export const TALLAS = ['XS', 'S', 'M', 'L', 'XL']

export const productos = [
  {
    id: 1,
    nombre: 'Camisa negra',
    descripcion: 'Manga corta, algodón peinado',
    categoria: 'Tops',
    proveedor: 'PROV1',
    precio: 12000,
    precioAnterior: null,
    stock: 10,
    tallas: ['XS', 'S', 'M', 'L'],
    calificacion: 4.7,
    imagen: '/img/productos/camisa.jpg',
    etiqueta: null,
  },
  {
    id: 2,
    nombre: 'Pantalón recto',
    descripcion: 'Tiro alto, mezclilla negra',
    categoria: 'Pantalones',
    proveedor: 'PROV2',
    precio: 18500,
    precioAnterior: 22000,
    stock: 15,
    tallas: ['S', 'M', 'L', 'XL'],
    calificacion: 4.5,
    imagen: '/img/productos/pantalon.jpg',
    etiqueta: 'Descuento 15%',
  },
  {
    id: 3,
    nombre: 'Vestido midi',
    descripcion: 'Falda amplia, tela fresca',
    categoria: 'Vestidos',
    proveedor: 'PROV1',
    precio: 24000,
    precioAnterior: null,
    stock: 10,
    tallas: ['XS', 'S', 'M'],
    calificacion: 4.8,
    imagen: '/img/productos/vestido.jpg',
    etiqueta: 'Nueva colección',
  },
  {
    id: 4,
    nombre: 'Tenis old school',
    descripcion: 'Lona blanca y negra, suela de goma',
    categoria: 'Calzado',
    proveedor: 'PROV3',
    precio: 26000,
    precioAnterior: null,
    stock: 5,
    tallas: ['S', 'M', 'L'],
    calificacion: 4.6,
    imagen: '/img/productos/tenis.jpg',
    etiqueta: null,
  },
  {
    id: 5,
    nombre: 'Top corto',
    descripcion: 'Escote cruzado, satinado',
    categoria: 'Tops',
    proveedor: 'PROV2',
    precio: 20000,
    precioAnterior: null,
    stock: 12,
    tallas: ['XS', 'S', 'M', 'L'],
    calificacion: 4.9,
    imagen: '/img/productos/top-corto.jpg',
    etiqueta: 'Nueva colección',
  },
  {
    id: 6,
    nombre: 'Vestido vintage Y2K',
    descripcion: 'Estampado retro, corte asimétrico',
    categoria: 'Vestidos',
    proveedor: 'PROV1',
    precio: 12500,
    precioAnterior: 16000,
    stock: 8,
    tallas: ['S', 'M', 'L'],
    calificacion: 4.4,
    imagen: '/img/productos/vestido-y2k.jpg',
    etiqueta: 'Descuento 20%',
  },
]

export const buscarProducto = (id) => productos.find((p) => p.id === Number(id))
